Feature/op cli configuration on app side
1Password/kubernetes-secrets-injector pull request #11
Opened 2022-10-04 10:18 UTC by volodymyrZotov

2022-10-04 17:16 UTC, kpcraig commented on pkg/webhook/k8s-client.go
> -/*
it seems like maybe the differ has gotten a bit confused with renaming/moving/new file adding, so i'm curious what this copyright was attached to.

2022-10-04 18:42 UTC, volodymyrZotov commented on pkg/webhook/k8s-client.go
> -/*
@kpcraig I think [this repo](https://github.com/morvencao/kube-sidecar-injector) was taken as an inspiration for the injector, and the copyright most probably comes from there.
Do you think we should return in back?

2022-10-05 15:17 UTC, kpcraig commented on pkg/webhook/k8s-client.go
> -/*
If we derived our code from their code, then it's probably appropriate to include a notice in some way. I'm not a lawyer but something like

"This project includes work covered by the following copyright and permission notices:
 -  Copyright 2022 Morvenco
 -  Licensed under the Apache License, Version 2.0 (the "License")
 
 You may obtain a copy of the Apache License at:
 http://www.apache.org/licenses/LICENSE-2.0"

in a `LICENSE` file might work.

2022-10-05 15:33 UTC, edif2008 commented on pkg/webhook/k8s-client.go
> -/*
Indeed the content of this file came from the repo Volodymyr mentioned and it's about creating the certificates on the fly or use them if they're already created.

I did add the licence notice at the beginning of the code to be safe regarding the copyright side of it. 
There are two parts of the file (from the repo):
- Creating the webhook config -> this is trivial and if you want to do such a resource, 99% the code will be identical. Therefore, this part may not be the one to trigger any copyright issues
- Looking for the config and update it if needed -> this part looks non-trivial and thus should fall under the copyright.

Looking at the code now it feels like we have made quite some changes to it. I'm not sure if the final result resembles any of the used code, but if so, then using Kay's suggestion seems the appropiate approach.

2022-10-06 08:25 UTC, volodymyrZotov commented on pkg/webhook/k8s-client.go
> -/*
I reverted it

2022-10-11 18:39 UTC, jillianwilson approved these changes

2022-10-17 12:59 UTC, edif2008 requested changes
Functional review: ✅ 
It definitely feels like a better injector that is simpler to deploy and should work for a broader range of use cases.

Two remarks I have here:
- Please validate if auto-restarts works with the k8s operator. We don't want to give false expectations.

- I've noticed a stange behavior. When I deleted, then re-deployed the `deployment.yaml`, the entire injector broke with a weird error:
  ```
  2022/10/17 11:41:44 http: TLS handshake error from 172.17.0.1:40140: remote error: tls: bad certificate
  ```

  This makes me thing that the TLS certificate is not properly deleted when the injector is deleted as well, which makes things weird. Maybe redeploying the service fixes this scenario? Would you validate this for me? Thanks 😄 

Code review: ✅ 
A couple of important things to make this better:
- Simplify the way we get the token from the pod. Let the built-in k8s do the work in providing the secret value the user wants to pass. This should have an big impact on the code and what we do
- I see that the `k8sClient` only does the follwing: initialize client and create/update webhook config. Although I see the value of wrapping the functionality into a custom struct, it doesn't bring a lot of value in this use case. Therefore, I'd remove this wrapper which will simplify the code for now. We can wrap it later when things get more complex and it feels more natural to do so. <br> We can keep it if we'd also make on the spot the things we deploy with `permissions.yaml` (`ServiceAccount`, `ClusterRole`, and `CLusterRoleBinding`). Otherwise, I'd simplify this code to just have a nicer way of creating this resource.
- Put the `k8s-client` in a separate package to make things a bit cleaner.
- Rename `webhook_suit_test` to just `suite_test` (also you have a typo, it should be `suite`). Since we're in the `webhook` package, we know that it's a suit test for it.
- Add the tests that were removed, since they're still relevant.

2022-10-17 12:59 UTC, edif2008 commented on deploy/permissions.yaml
> +  namespace: default
Why do we need to add a namespace here?

2022-10-17 12:59 UTC, edif2008 commented on README.md
> +[Click here for more details on the 1Password Kubernetes Operator](https://github.com/1Password/onepassword-operator)
Can it really do it? Has this been validated?

From what I know the auto-restarts check for the OnePasswordItem resources and based on these updates they can do the restarts. The injector doesn't use such resources. 🤔

2022-10-17 12:59 UTC, edif2008 commented on deploy/permissions.yaml
> +    verbs: ["get"]
Why do we need these new rules?

2022-10-17 12:59 UTC, edif2008 commented on deploy/permissions.yaml
> +    namespace: default
Why do we need to add a namespace here?

2022-10-17 12:59 UTC, edif2008 commented on pkg/webhook/k8s-client.go
> +	MutatingWebhookConfigV1Client := c.Clientset.AdmissionregistrationV1()
Since this is a local variable, it doesn't need to be capitalised (i.e. exported)

2022-10-17 12:59 UTC, edif2008 commented on pkg/webhook/webhook.go
> +	serviceAccountSecretNameEnv = "OP_SERVICE_ACCOUNT_SECRET_NAME"
Since we no longer do the config at the webhook level, we can simplify this part.

For Connect, we'll only need:
- `OP_CONNECT_HOST`
- `OP_CONNECT_TOKEN` 

For Service Accounts, we'd only need:
- `OP_SERVICE_ACCOUNT_TOKEN`

For the token, we can either pass the raw value or the secret with `valueFrom` parameter. This makes use of k8s' built-in deployment management depending on whether the secret exists or not, which simplifies the injector's functionality even more (i.e. we no longer need to do checks for secrets and such).

2022-10-17 12:59 UTC, edif2008 commented on pkg/webhook/webhook.go
> +	defaultOpCLIVersion             = "2"
If we want to support service accounts, we should change this to `2-beta`

2022-10-17 12:59 UTC, edif2008 commented on pkg/webhook/webhook_test.go
> -	}
This test was removed from this file, but not placed anywhere else.
While I do understand that it doesn't belong to this specific file, it should still be part of the tests we have for the injector. 

This test can be run outside the `ginkgo` environment by putting it in a separate file e.g. `build_version_test.go`. they help in ensuring that we make the build version string properly.

2022-10-17 12:59 UTC, edif2008 commented on README.md
> +        - name: app-example2
Did you mean `app-example-3` here?

2022-10-17 12:59 UTC, edif2008 commented on README.md
>          - name: app-example
Now that you've changed the annotation, then this container name no longer matches any of the provided ones in the annotation. This means that in this case, this container will be skipped. You should rename it to `app-example1` to make this example work again.

2022-10-17 12:59 UTC, edif2008 commented on README.md
> +- `YOUR_OP_SERVICE_ACCOUNT_TOKEN` - your Service Account token
If we will simplify how to provide the token, we should reflect this in the README.

2022-10-17 12:59 UTC, edif2008 commented on README.md
> +- `YOUR_OP_CONNECT_TOKEN` - your Connect token
If we will simplify how to provide the token, we should reflect this in the README.

2022-10-17 12:59 UTC, edif2008 commented on pkg/webhook/webhook_test.go
> +	})
What do these tests do? I don't see any connection between these and our webhook. It feels like you test something that should already be tested by folks who made the packages we use, thus it shouldn't be our concern to test this as well. 🤔

2022-10-17 12:59 UTC, edif2008 commented on pkg/webhook/webhook_test.go
> +			It("should NOT create patch", func() {
Noticed this line in all tests. This makes me think that these tests can be optimised, since we test the same thing in different scenarios. It's like only the input is different, but the same output is expected.

2022-10-17 12:59 UTC, edif2008 commented on pkg/webhook/webhook_test.go
> +	// TODO: cover cases when patch is created, check it contains env vars, volumes etc.
Will this be part of this PR or another one?

2022-10-17 12:59 UTC, edif2008 commented on pkg/webhook/webhook_test.go
> +package webhook_test
Why is this changed? It is part of the `webhook` package and not `webhook_test` package. This makes things a bit odd in terms of Go practices.

2022-10-17 12:59 UTC, edif2008 commented on cmd/main.go
> +	err = webhook.K8sClient.CreateOrUpdateMutatingWebhookConfiguration(caPEM, webhookServiceName, webhookNamespace)
this looks a bit weird from a Go perspective, I'd expect something like:
```
err = k8sClient.CreateOrUpdateMutatingWebhookConfiguration(caPEM, webhookServiceName, webhookNamespace)
```

To fix this, move `k8s-client.go` (which should have the name `k8s_client.go` or even `k8sclient.go`) into a separate package. Maybe `pkg/k8s/client.go` or `pkg/k8sclient/k8s_client.go`?

2022-10-17 12:59 UTC, edif2008 commented on pkg/webhook/webhook.go
> +	defaultDataKey                  = "token"
If we will simplify how we get this data, I think some of these vars should be removed as well.

2022-10-17 13:23 UTC, edif2008 commented on deploy/permissions.yaml
> +    namespace: default
I went deeper into this and this is a place where the `namespace` is a required field.
The problem with that is that it can affect how we deploy these easily.
In this case we need to mention the namespace the service account is deployed. If it's deployed in another namespace, this file no longer works. We have two options:
- Inform the user to adjust this namesapce depending on where they want to apply the `permissions.yaml` file.
- Make these resources ourselves (in Go code). In this way, we may have a bit more flexibility in how we deploy these and thus the user shouldn't be worried about these being wrongly deployed.

It'd help to investigate this and see which option is more suitable.

2022-10-20 08:29 UTC, volodymyrZotov commented on deploy/permissions.yaml
> +    verbs: ["get"]
To be able to get secrets in the code using `k8sClient` library.

2022-10-20 08:30 UTC, volodymyrZotov commented on pkg/webhook/webhook_test.go
> +	// TODO: cover cases when patch is created, check it contains env vars, volumes etc.
I think another one

2022-10-20 08:31 UTC, volodymyrZotov commented on pkg/webhook/webhook_test.go
> +package webhook_test
This is what `ginkgo` framework [suggests to do when writing tests](https://onsi.github.io/ginkgo/#bootstrapping-a-suite).

2022-10-20 10:02 UTC, volodymyrZotov commented on pkg/webhook/webhook.go
> +	defaultOpCLIVersion             = "2"
This can be achieved by applying `version` annotation and providing op version explicitly.
But in general, we can change this variable if that's fine to use `beta` version by default

2022-10-20 10:06 UTC, volodymyrZotov commented on pkg/webhook/webhook_test.go
> +	})
Those test the source code that we wrote in `webhook.go`.
For example there is a part from webhook that is covered by `It("should return bad request if no body provided",`

```if len(body) == 0 {
		glog.Error("empty body")
		http.Error(w, "empty body", http.StatusBadRequest)
		return
	}```

2022-10-20 10:23 UTC, edif2008 commented on pkg/webhook/webhook.go
> +	defaultOpCLIVersion             = "2"
We'll stick to version 2 as the default here. 😄

2022-10-20 10:36 UTC, edif2008 commented on pkg/webhook/webhook_test.go
> +	})
Understood. Thanks for the clarification. Then we will keep these tests. 😄

2022-10-20 10:40 UTC, edif2008 commented on pkg/webhook/webhook_test.go
> +package webhook_test
I see. Thank you for the explanation.

For this case, however, as discussed, we will change it to `webhook` to have a similar pattern to what we have at the operator.

2022-10-20 10:42 UTC, edif2008 commented on pkg/webhook/webhook_test.go
> -	}
Added the test and adjusted a bit the code to highlight that the test is executed in an isolated environment from `ginkgo`.

2022-10-20 14:16 UTC, edif2008 commented on deploy/permissions.yaml
> +    verbs: ["get"]
They're no longer needed since the k8s Client we use no longer looks for secrets.

2022-10-20 14:16 UTC, edif2008 commented on deploy/permissions.yaml
> +  namespace: default
Namespace was removed from here.

2022-10-21 14:47 UTC, volodymyrZotov commented on deploy/permissions.yaml
> +    namespace: default
I made it populated dynamically.
Starting from now all we need to do to deploy is `make deploy` which will use `kustomize` under the hood and set the current kubectl's namespace for all the resources.

2022-10-21 14:48 UTC, volodymyrZotov commented on README.md
> +[Click here for more details on the 1Password Kubernetes Operator](https://github.com/1Password/onepassword-operator)
I made an investigation, so injector  doesn't support  auto-restart feature.

2022-10-21 14:48 UTC, volodymyrZotov commented on README.md
> +[Click here for more details on the 1Password Kubernetes Operator](https://github.com/1Password/onepassword-operator)
I'll just remove this section from readme

2022-10-24 09:57 UTC, edif2008 requested changes
Functional review: ✅ 
Deploying the webhook is so much smoother now. I love it! ❤️ 

Code review: ✅ 
Code looks solid and clean. We should be good now. Left a couple of comments to make it a bit better.

One remark that I have:
We do now install `kustomize`, but I noticed that the `bin` directory created is not ignored. I think it would be a good idea to ignore it, since this is created when deploying and the `kustomize` used can differ based on OS and architecture.

2022-10-24 09:57 UTC, edif2008 commented on README.md
> +- [Example](#example)
Usually this section would be called `Usage` since we show how to make use of the webhook in other pods.

2022-10-24 09:57 UTC, edif2008 commented on pkg/webhook/webhook.go
> +}
This function is not used, therefore it can be removed.

2022-10-24 09:57 UTC, edif2008 commented on pkg/webhook/webhook.go
> +	defaultConnectHost  = "http://onepassword-connect:8080"
This constant is no longer used, thus it can be removed.

2022-10-24 09:57 UTC, edif2008 commented on pkg/webhook/webhook.go
> +func isEnvVarSetup(envVarName string) func(c *corev1.Container) bool {
Why do we return a function here instead of just the `bool`? It feels like you overcomplicated this function a bit.

I feel like this simplified function will do the same thing:
```go
func isEnvVarSetup(envVarName string, container *corev1.Container) bool {
	envVar := findContainerEnvVarByName(envVarName, container)
	if envVar == nil {
		glog.Infof("%s not provided", envVarName)
	}
	return envVar != nil
}
```

2022-10-24 09:57 UTC, edif2008 commented on README.md
> +### 5. Annotate your client pod/deployment with the minimum op-cli version  annotation that supports Service Accounts `2.8.0-beta.05`
This is too long for a heading. Think about making it shorter and add the details as a separate paragraph.
One idea would be `Annotate your deployment`.

2022-10-24 09:57 UTC, edif2008 commented on README.md
> +### 5. Annotate your client pod/deployment spec with `operator.1password.io/inject` which expects a comma separated list of the names of the containers to that will be mutated and have secrets inject
This is too long for a heading. Think about making it shorter and add the details as a separate paragraph.
One idea would be `Annotate your deployment`.

2022-10-24 09:57 UTC, edif2008 commented on README.md
> +### 6. Add an environment variable to the resource with a value referencing your 1Password item in the format `op://<vault>/<item>[/section]/<field>`.
Same here. Suggested heading: `Configure resource's environment`

2022-10-24 09:57 UTC, edif2008 commented on README.md
> +### 5. Add an environment variable to the resource with a value referencing your 1Password item in the format `op://<vault>/<item>[/section]/<field>`.
Same here. Suggested heading: Configure `resource's environment`

2022-10-24 09:57 UTC, edif2008 commented on README.md
> +- [Provide `op-cli` credentials on your app pod/deployment](#provide-op-cli-credentials-on-your-app-poddeployment)
`op-cli` is not that great of a name. We barely used it. Therefore, it would confuse a bit the users and it would add inconsistency across documentation. Suggested name is `1Password CLI`.

2022-10-24 11:21 UTC, volodymyrZotov commented on pkg/webhook/webhook.go
> +func isEnvVarSetup(envVarName string) func(c *corev1.Container) bool {
To make those:
```
func isConnectHostEnvVarSetup(container *corev1.Container) bool {
	return isEnvVarSetup(connectHostEnv)(container)
}

func isConnectTokenEnvVarSetup(container *corev1.Container) bool {
	return isEnvVarSetup(connectTokenEnv)(container)
}

func isServiceAccountEnvVarSetup(container *corev1.Container) bool {
	return isEnvVarSetup(serviceAccountTokenEnv)(container)
}
```

In that case, the function name tells exactly what variable we are looking for.
That makes it easier to understand what happens inside `checkOPCLIEnvSetup` function. As per my opinion 😄
```
func checkOPCLIEnvSetup(container *corev1.Container) {
	isConnectSetup := isConnectTokenEnvVarSetup(container) && isConnectHostEnvVarSetup(container)
	isServiceAccountSetup := isServiceAccountEnvVarSetup(container)
......
```

Your example is a good one and does its work perfectly!
I just like to use some functional programming features 😄

We can stick with your one variant if you think it's easier to follow.

2022-10-24 11:22 UTC, volodymyrZotov commented on pkg/webhook/webhook.go
> +	defaultConnectHost  = "http://onepassword-connect:8080"
done

2022-10-24 11:22 UTC, volodymyrZotov commented on pkg/webhook/webhook.go
> +}
done

2022-10-24 11:22 UTC, volodymyrZotov commented on README.md
> +- [Example](#example)
changed

2022-10-24 11:23 UTC, volodymyrZotov commented on README.md
> +### 5. Annotate your client pod/deployment with the minimum op-cli version  annotation that supports Service Accounts `2.8.0-beta.05`
changed

2022-10-24 11:26 UTC, volodymyrZotov commented on README.md
> +### 6. Add an environment variable to the resource with a value referencing your 1Password item in the format `op://<vault>/<item>[/section]/<field>`.
changed

2022-10-24 11:27 UTC, volodymyrZotov commented on README.md
> +### 5. Add an environment variable to the resource with a value referencing your 1Password item in the format `op://<vault>/<item>[/section]/<field>`.
changed

2022-10-24 11:31 UTC, volodymyrZotov commented on README.md
> +- [Provide `op-cli` credentials on your app pod/deployment](#provide-op-cli-credentials-on-your-app-poddeployment)
changed

2022-10-24 14:03 UTC, edif2008 approved these changes

2022-10-24 14:34 UTC, jillianwilson commented on pkg/webhook/webhook.go
> +func isEnvVarSetup(envVarName string) func(c *corev1.Container) bool {
Either is valid, I think it's honestly a matter of personal preference, though going the non functional route may make it easier for outside contributors to pick up what's going on.

2022-10-27 09:37 UTC, edif2008 commented on pkg/webhook/webhook.go
> +func isEnvVarSetup(envVarName string) func(c *corev1.Container) bool {
Then we will stick with the functional approach for this one. It's interesting to have it and it gets the job done 😄

2022-10-27 15:19 UTC, merged