Update readme to remove ambiguity
1Password/kubernetes-secrets-injector pull request #40
Opened 2023-07-14 20:48 UTC by plttn

2023-07-14 21:31 UTC, ag-adampike requested changes
A few minor clerical edits.

2023-07-14 21:31 UTC, ag-adampike commented on README.md
> +Provide your pod or deployment with 1Password CLI credentials to perform the injection. One possibility to safely provide these secrets is to [create Kubernetes Secrets](#step-1-create-a-kubernetes-s
```suggestion
Provide your Pod or Deployment with 1Password CLI credentials to perform the injection. One possibility to safely provide these secrets is to [create a Kubernetes Secret](#step-1-create-a-kubernetes-secret-containing-opserviceaccounttoken) and refer to them in your deployment configuration.
```

2023-07-14 21:31 UTC, ag-adampike commented on README.md
> +Provide your pod or deployment with 1Password CLI credentials to perform the injection. One possibility to safely provide these secrets is to [create Kubernetes Secrets](#step-1-create-a-kubernetes-s
```suggestion
Provide your Pod or Deployment with 1Password CLI credentials to perform the injection. One possibility to safely provide these credentials is to [create a Kubernetes Secret](#step-1-create-a-kubernetes-secret-containing-opconnecttoken) and refer to them in your deployment configuration.
```

2023-07-14 21:31 UTC, ag-adampike commented on README.md
> +**NOTE:** The injector creates the TLS certificate required for the webhook to work on the fly when deploying the injector (`deployment.yaml`). When the injector is removed from the cluster, it will
Perhaps consider linking to the file:

```suggestion
**NOTE:** The injector creates the TLS certificate required for the webhook to work on the fly when deploying the injector ([`deployment.yaml`](/deploy/deployment.yaml)). When the injector is removed from the cluster, it will delete the certificate.
```

2023-07-14 21:31 UTC, ag-adampike commented on README.md
> +To inject secrets, the container you're looking to inject into must have a `command` defined. The 1Password Secrets Injector works by mutating the `command` on init, and as such a command is needed t
Clarifying some things, linking to reference docs:

```suggestion
To inject secrets, the Pod you're looking to inject into must have a `command` value defined in its [Deployment or Pod spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#container-v1-core). The 1Password Secrets Injector works by mutating the this value on initilization, and as such a command is needed to be mutated. If the deployments you're using aren't designed to have `command` specified in the deployment, then the 1Password Kubernetes Operator may be a better fit for your use case.
```

2023-08-01 16:43 UTC, volodymyrZotov approved these changes
Looks more clearer and solid right now! Thank you @plttn !

2023-08-01 16:43 UTC, merged